name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u sasaplus1 -p "${{ secrets.GITHUB_TOKEN }}" docker.pkg.github.com
      - run: docker build -t docker.pkg.github.com/${{ github.repository }}/madge:${GITHUB_REF##refs/tags/} .
      - run: docker push docker.pkg.github.com/${{ github.repository }}/madge:${GITHUB_REF##refs/tags/}
